import os
from datetime import datetime
from typing import Dict, List
from .models import ScenarioResult

def save_scenario_md(result: ScenarioResult, output_dir: str = r"d:\VITRIFY\reports\markdown_breakdowns"):
    """
    Save a detailed scenario breakdown to a Markdown file.
    """
    os.makedirs(output_dir, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = result.scenario_name.replace(" ", "_").lower()
    filename = f"breakdown_{safe_name}_{timestamp}.md"
    filepath = os.path.join(output_dir, filename)
    
    with open(filepath, "w", encoding="utf-8") as f:
        # Title
        f.write(f"# Emission Breakdown: {result.scenario_name}\n")
        f.write(f"**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        
        # Summary Stats
        f.write("## Summary\n")
        f.write(f"- **Total Emissions**: {result.total_emissions_kgco2:.4f} kgCO2e\n")
        f.write(f"- **Material Yield**: {result.yield_percent:.1f}%\n")
        f.write(f"- **Recovered Mass**: {result.final_mass_kg:.2f} kg (from {result.initial_mass_kg:.2f} kg)\n\n")
        
        # Detailed Table
        f.write("## Detailed Breakdown\n")
        f.write("| Stage | Emissions (kgCO2e) | Contribution (%) |\n")
        f.write("| :--- | :--- | :--- |\n")
        
        total = result.total_emissions_kgco2
        sorted_stages = sorted(result.by_stage.items(), key=lambda x: x[1], reverse=True)
        
        for stage, val in sorted_stages:
            pct = (val / total * 100.0) if total > 0 else 0.0
            f.write(f"| {stage} | {val:.4f} | {pct:.1f}% |\n")
            
        f.write(f"| **TOTAL** | **{total:.4f}** | **100.0%** |\n")
        
        f.write("\n---\n")
        f.write("*Generated by IGU Recovery Analysis Tool*")
        
    print(f"\n[Report] Saved detailed Markdown breakdown to:\n  -> {filepath}")
    return filepath
